Add times, dates and stations datasets
alexandrainst/tts_text pull request #1
Opened 2023-10-24 15:15 UTC by saattrupdan

This PR adds the following:

1. A dates dataset, with day, month and year
2. A times dataset, with hour and minute, as well as expressions such as "kvart i fire"
3. A script that interleaves them according to given sampling probabilities
4. Setup of docker - running `make docker` will build the dataset in the `data` folder.

2023-10-25 12:33 UTC, AJDERS requested changes
Almost LGTM, minor change

2023-10-25 12:33 UTC, AJDERS commented on src/tts_text/dates.py
> +YEARS = [year for year in range(2000, 2030)]
Maybe also include a few years before 2000?

2023-10-25 12:35 UTC, saattrupdan commented on src/tts_text/dates.py
> +YEARS = [year for year in range(2000, 2030)]
Added 1970-1999 as well now

2023-10-26 08:13 UTC, AJDERS approved these changes
LGTM!

2023-10-26 08:14 UTC, merged