Feat/reddit data
alexandrainst/tts_text pull request #6
Opened 2023-10-26 12:44 UTC by AJDERS

Adds reddit data. We remove stuff with URLs and also only use texts which are almost surely danish.

2023-10-26 13:20 UTC, saattrupdan commented
Unfortunately, we can't just add all of Reddit, since there are profane things in there. We have to go over each sample manually, and only use the ones that we have reviewed. Maybe you can setup a script to review the samples, and upload the samples to a separate dataset on the hub?

2023-10-27 09:49 UTC, saattrupdan requested changes

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +@click.option("--n", type=int, default=1000)
I would include more info here. I'm guessing this is the number of samples to annotate:

```suggestion
@click.option("--num-samples=", "-n", type=int, default=1000, help="The number of samples to annotate")
```

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +@click.option("--start-index", type=int, default=0)
```suggestion
@click.option("--start-index", type=int, default=0, help="The sample index to start annotating from.")
```

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +@click.option("--username", type=str, required=True)
```suggestion
@click.option("--username", type=str, required=True, help="The username of the person filtering the dataset.")
```

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +    """
This is not needed when using `click`:
```suggestion
def filter_reddit_dataset(output_dir, username, n, start_index):
    """Script for manually filtering a list of reddit comments."""
```

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +    print("Hello and welcome to the reddit comment filtering tool!")
Logging?

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +    # Load the previous answers, if any exist
```suggestion

    # Load the previous answers, if any exist
```

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +            print("Previous filtering found, merging with new filtering.")
Logging?

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +    print(f"Sentence {start_index + index}: {sentence}")
Logging?

2023-10-27 09:49 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +        records = prompt_user(answer, records, sentence, username, start_index, index)
Kwargs instead of args

2023-10-27 09:49 UTC, saattrupdan commented on src/tts_text/reddit.py
> +            )
Missing `split`

2023-10-27 09:49 UTC, saattrupdan commented on src/tts_text/reddit.py
> +    )
Should only be called if using CSV

2023-10-27 09:49 UTC, saattrupdan commented on src/tts_text/reddit.py
> +        token=os.environ["HF_HUB_TOKEN"],
```suggestion
        token=os.getenv("HF_HUB_TOKEN", True),
        exist_ok=True,
        private=True,
    )
    filtered_comments.push_to_hub(
        repo_id="alexandrainst/scandi-reddit-manually-filtered",
        token=os.getenv("HF_HUB_TOKEN", True),
```

2023-11-14 15:11 UTC, AJDERS commented
I have annotated the first 1000 comments, and put it on hf:
https://huggingface.co/datasets/alexandrainst/scandi-reddit-filtered

In general i **have** removed comments if:

1. Misspelling
2. Typesetting which is not read out loud, such as ";", "-" and "()".
3. If any words were in caps.
4. Explicitly racist or misogynistic.

Comments were **not** removed if:

1. Abbreviations, which are read out loud, such at "bl.a." and "f.eks."
1. They are discussing wether other people are racist. (surprising volume of this particular topic)
2. Comments with "?" and "!", and "%".

2023-11-22 12:50 UTC, saattrupdan requested changes

2023-11-22 12:50 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +    # Manually filter the dataset, and store which person filtered each comment
```suggestion
    ]
    
    # Manually filter the dataset, and store which person filtered each comment
```

2023-11-22 12:50 UTC, saattrupdan commented on src/scripts/manually_filter_reddit_comments.py
> +        answer = input("Keep? [y/n]: ")
Include the 'skip' option

2023-11-22 12:50 UTC, saattrupdan commented on src/tts_text/reddit.py
> +
Not needed?

```suggestion
```

2023-11-22 12:50 UTC, saattrupdan commented on src/tts_text/reddit.py
> +        if all(answer == "y" for answer in comment["keep"].split(" ,"))
Should this be splitting by ", " instead of " ,"?

```suggestion
        if all(answer == "y" for answer in comment["keep"].split(", "))
```

2023-11-22 13:05 UTC, saattrupdan approved these changes
LGTM!

2023-11-22 13:09 UTC, merged